### ISSUE TITLE
delete_regkey() closes the wrong handle in function cleanup resulting in a leaked registry handle

### ISSUE THREAD

**Issue by JohnLaTwC** [trustedsec/CS-Remote-OPs-BOF#1]
`delete_regkey` closes the wrong handle in function cleanup resulting in a leaked registry handle.

This looks like a copy/paste error.  `RemoteKey` is not closed.

```diff
delete_regkey_end:
	if(RemoteKey)
	{
-		ADVAPI32$RegCloseKey(rootkey);
+		ADVAPI32$RegCloseKey(RemoteKey);
-		rootkey = NULL;
+		RemoteKey = NULL;
	}

	if(rootkey)
	{
		ADVAPI32$RegCloseKey(rootkey);
		rootkey = NULL;
	}
	
	if(targetkey)
	{
		ADVAPI32$RegCloseKey(targetkey);
		targetkey = NULL;
	}
```

https://github.com/trustedsec/CS-Remote-OPs-BOF/blob/1f00c7ba846f49d27f4725effc9fca36b6bd082d/src/Remote/reg_delete/entry.c#L65

**Comment by freefirex** [comment]
Thanks for the catch :)  Given past experience I'll wait a few days for you to finish combing through and then I'll fix up anything you've found.
