### ISSUE TITLE
security bug: createTask calls VariantInit on uninitialized VARIANT in error cases

### ISSUE THREAD

**Issue by JohnLaTwC** [trustedsec/CS-Remote-OPs-BOF#4]
There is a small security bug in `createTask` where, in an error branch, several VARIANTs will be uninitialized and the code calls VariantClear on them.   Recommend moving the variant initialization before the gotos.

```diff
DWORD createTask(const wchar_t * server, wchar_t * taskpath, const wchar_t* xmldef, int mode, BOOL force)
{
	HRESULT hr = S_OK;
	VARIANT Vserver;
	VARIANT VNull;
	VARIANT Vsddl;
	VARIANT Vthisuser;
@@ NOTE: VARIANTs are uninitialized at this point @@
...


	// Initialize COM
	hr = OLE32$CoInitializeEx(NULL, COINIT_APARTMENTTHREADED);
	if(FAILED(hr))
	{
		internal_printf("Failed to initialize COM (%lX)\n", hr);
!		goto createTask_end;  <<< jumps to cleanup before initializing variants
	}

	// Create System user string
	BSTRsystem = OLEAUT32$SysAllocString(USER_SYSTEM_STRING);
	if (NULL == BSTRsystem)
	{
		hr = ERROR_OUTOFMEMORY;
		internal_printf("SysAllocString failed (%lX)\n", hr);
!		goto createTask_end;     <<< jumps to cleanup before initializing variants
	}

	// Initialize variants
	OLEAUT32$VariantInit(&Vserver);
	OLEAUT32$VariantInit(&VNull);
	OLEAUT32$VariantInit(&Vsddl);
	OLEAUT32$VariantInit(&Vthisuser); // we don't clear this because we free both possible OLE strings
@@ NOTE: NOW VARIANTs are initialized @@
...


createTask_end:
...

!	OLEAUT32$VariantClear(&Vsddl);   <<<  security bug from calling VariantClear on uninitialized variant 💥
!	OLEAUT32$VariantClear(&Vserver); <<<  security bug from calling VariantClear on uninitialized variant 💥
 	//OLEAUT32$VariantInit(&Vthisuser); // we don't clear this because we free both possible OLE strings
	OLE32$CoUninitialize();

	return (DWORD)hr;
}
```

See (https://docs.microsoft.com/en-us/windows/win32/api/oleauto/nf-oleauto-variantclear)

> Do not use VariantClear on uninitialized variants; use VariantInit to initialize a new VARIANTARG or VARIANT.

https://github.com/trustedsec/CS-Remote-OPs-BOF/blob/37735ae7df62a35b8ab033394e62daa1fc733e5b/src/Remote/schtaskscreate/entry.c#L523

Similar issue in `deleteTask()`:
https://github.com/trustedsec/CS-Remote-OPs-BOF/blob/37735ae7df62a35b8ab033394e62daa1fc733e5b/src/Remote/schtasksdelete/entry.c#L173

Similar issue in `stopTask()`:
https://github.com/trustedsec/CS-Remote-OPs-BOF/blob/37735ae7df62a35b8ab033394e62daa1fc733e5b/src/Remote/schtasksstop/entry.c#L153

**Comment by freefirex** [comment]
Thanks again!
